spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eliHandy6/environment-environment-repo.git
          default-label: main


server:
  port: ${port:8888}








